### ISSUE TITLE
not auto-updating?

### ISSUE THREAD

**Issue by gforcada** [collective/collective.eggproxy#1]
Hi,

I'm using collective.eggproxy and looking at the docs on pypi it seems that it should auto-update by itself, i.e you do not need to run the ./bin/eggproxy_run with a cron job.

Though, looking at the code of wsgi.py its clear that is not[1], it only looks if the file exists and if it does and you do not explicitly say to always refresh you will never get new updates.

If that was the intended design, then this should be documented so that when you go to its pypi page you clearly know that you have to add something like:

[buildout]
parts =
    ...
    cron-update

[cron-update]
recipe = z3c.recipe.usercrontab
times = 30 \* \* \* *
command = ${buildout:directory}/bin/eggproxy_update

If not, as new releases of distributions that you use are available you will have to manually run eggproy_run. 

[1] https://github.com/collective/collective.eggproxy/blob/master/collective/eggproxy/wsgi.py#L85

**Comment by mauritsvanrees** [comment]
According to http://pypi.python.org/pypi/collective.eggproxy#advanced-configuration the default is to to not auto update.  You can change that in buildout.cfg by setting always_refresh = 1, as noted in that section on PyPI.

If you have a suggestion for making the docs clearer on this point, that is welcome.

**Comment by jcook793** [comment]
I had the same problem, it seems like new versions never show up in the cache.  I added always_refresh=1 in the config but they still don't show up.  I'll try to play around and see if I can figure out what's going on.

**Comment by jcook793** [comment]
As it turned out, my problem was that I was using the ancient mod_python and that handler doesn't honor the always_refresh configuration.  I switched to the WSGI app instead.

It seems that the app could pretty easily do what isOutDated() in update_script.py does on every request.  That would be a good compromise between _always_ checking PyPi and having to setup a cron job.

I'll throw together a pull request and see what you think.

**Comment by jcook793** [comment]
Pull request:  https://github.com/collective/collective.eggproxy/pull/3

**Comment by mauritsvanrees** [comment]
Normally it should not be necessary, as files in PyPI should never be changed, but that is unfortunately not always true. This may explain why I sometimes need to go to my internal pypi server and manually remove a few files so they can get downloaded again with a correct md5 sum. It looks like I am using mod_python too BTW.

Patch looks good, but I have not tried it and I don't have rights on PyPI to make a new release anyway, so I will let someone else to the pulling.

**Comment by jcook793** [comment]
Well I think it becomes a problem when new versions of a package are released.  When that happens, the package index file (for instance: http://pypi.python.org/simple/collective.eggproxy/) changes.  If the package index is never checked, we'll never be able to discover the "latest" available version.

It would only be an issue if you use don't use version pinning.

I've thought about refactoring things so that using mod_python or mod_wsgi will give you the same behavior.  But (in my humble opinion) the mod_python functionality should be removed and people should be steered towards mod_wsgi.

**Comment by mauritsvanrees** [comment]
When I interpret my experiences correctly, I think that the downloaded tarballs/eggs/zipfiles are never updated, but the index.html is always updated. When I run into problems, I remove the old tarball and on the next try everything is fine again as the tarball now fits the new md5 sum that was already in the index.html.

For example, I at least remember this being needed somewhere last year when apparently all 'distribute' tarballs had been re-uploaded with a different md5 sum. I don't know what the reason was. Maybe someone changed a url in the package info and re-uploaded it.  The index.html was always updated so it contained the new md5 sums as indicated by the html it got from pypi.python.org/simple/distribute, but the already downloaded tarballs were never updated.

As long as you have always_refresh=1 I don't think there is a problem when you don't use version pinning; then again, I always pin all packages, so I would not know. :-)

**Comment by gforcada** [comment]
For years I'm not using it anymore, let's close it for now, if someone still wants to work on this, please re-open 😄
